module.exports = {
    "content": {
      "www_taskbooker_be_babysitten": {
        "key": "www_taskbooker_be_babysitten",
        "Breadcrumb1": "babysitten",
        "Breadcrumb1category": "Babysitten",
        "Breadcrumb2": "",
        "Breadcrumb2category": "",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw babysitter",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale babysitter via Taskbooker",
        "HeadlineDynamicContent": "Enkele babysitters die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Via Taskbooker kom je eenvoudig in contact met verschillende babysitters in jouw buurt. Je kiest zelf wie je op je kinderen laat babysitten. Via Taskbooker contacteer je verschillende babysitters om dan de voor jou perfecte babysitter uit te kiezen.",
        "Paragraph2": "Taskbooker is een netwerk van helpende handen. Wij verzamelen alle mensen die willen babysitten om jou te kunnen helpen. Nadat je op Taskbooker hebt aangegeven waar en wanneer je een babysit nodig hebt, brengen wij je in contact met babysitters in jouw buurt die jou kunnen helpen.",
        "Paragraph3": "Via Taskbooker houd je altijd de touwtjes in handen. Heb je specifieke vragen of opmerkingen? Geen probleem. Je hebt rechtstreeks contact met verschillende babysitters in jouw buurt en spreekt ook zelf een prijs met hen af.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/babysitten"
      },
      "www_taskbooker_be_babysitten_babysit-aan-huis": {
        "key": "www_taskbooker_be_babysitten_babysit-aan-huis",
        "Breadcrumb1": "babysitten",
        "Breadcrumb1category": "Babysitten",
        "Breadcrumb2": "babysit-aan-huis",
        "Breadcrumb2category": "Babysit aan huis",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw babysit aan huis",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale babysit aan huis via Taskbooker",
        "HeadlineDynamicContent": "Enkele babysitters die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Via Taskbooker vind je eenvoudig jouw babysit aan huis in jouw buurt. Je kiest zelf wie je op je kinderen laat passen. Via Taskbooker kom je in contact met verschillende mensen die bij jouw thuis komen babysitten. Daarna kies je zelf je ideale babysitter.",
        "Paragraph2": "Taskbooker is een netwerk van mensen die elkaar willen helpen. Wij verzamelen alle mensen die een centje willen bijverdienen door bij jou thuis te komen babysitten. Nadat je op Taskbooker hebt aangegeven waar en wanneer je een babysit nodig hebt, brengen wij je in contact met babysitters in jouw buurt",
        "Paragraph3": "Een babysit aan huis vinden was nog nooit zo eenvoudig. Heb je specifieke vragen of opmerkingen voor je babysit? Geen probleem. Je hebt rechtstreeks contact met verschillende babysitters in jouw buurt en spreekt ook zelf een prijs met hen af.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/babysitten/babysit-aan-huis"
      },
      "www_taskbooker_be_babysitten_kinderopvang": {
        "key": "www_taskbooker_be_babysitten_kinderopvang",
        "Breadcrumb1": "babysitten",
        "Breadcrumb1category": "Babysitten",
        "Breadcrumb2": "kinderopvang",
        "Breadcrumb2category": "Onthaalouder",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw kinderopvang",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale kinderopvang via Taskbooker",
        "HeadlineDynamicContent": "Enkele Taskers gespecialiseerd in kinderopvang",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Via Taskbooker vind je eenvoudig jouw kinderopvang in jouw buurt. Je kiest zelf wie je op je kinderen laat passen. Via Taskbooker kom je in contact met verschillende mensen die je kinderen willen opvangen. Daarna kies je zelf je ideale kinderopvang.",
        "Paragraph2": "Taskbooker is een netwerk van mensen die elkaar willen helpen. Op Taskbooker vind je alle kinderoppassers die jou willen helpen. Nadat je op Taskbooker hebt aangegeven wat voor kinderoppas je precies zoekt, brengen wij je in contact met geschikte personen in jouw buurt",
        "Paragraph3": "Een kinderoppas vinden in jouw buurt was nog nooit zo eenvoudig. Heb je specifieke vragen of opmerkingen voor je kinderoppas? Geen probleem. Je hebt rechtstreeks contact met verschillende personen in jouw buurt en spreekt ook zelf een prijs met hen af.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/babysitten/kinderopvang"
      },
      "www_taskbooker_be_babysitten_nanny": {
        "key": "www_taskbooker_be_babysitten_nanny",
        "Breadcrumb1": "babysitten",
        "Breadcrumb1category": "Babysitten",
        "Breadcrumb2": "nanny",
        "Breadcrumb2category": "Babysit aan huis",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw nanny",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale nanny via Taskbooker",
        "HeadlineDynamicContent": "Enkele nannies die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Via Taskbooker vind je eenvoudig een nanny in jouw buurt. Je kiest zelf wie je op je kinderen laat letten. Via Taskbooker kom je in contact met verschillende mensen die jou kunnen helpen. Daarna kies je zelf je ideale nanny.",
        "Paragraph2": "Taskbooker is een netwerk van mensen die elkaar willen helpen. Op Taskbooker vind je alle nannies die jou willen helpen. Nadat je op Taskbooker hebt aangegeven naar wat voor iemand je op zoek bent, brengen wij je in contact met geschikte nannies in jouw buurt",
        "Paragraph3": "Een nanny vinden in jouw buurt was nog nooit zo eenvoudig. Wil je enkele vragen stellen aan je nanny voor hij/zij begint? Geen probleem. Je hebt rechtstreeks contact met verschillende personen in jouw buurt en spreekt ook zelf een prijs met hen af.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/babysitten/nanny"
      },
      "www_taskbooker_be_babysitten_onthaalouder": {
        "key": "www_taskbooker_be_babysitten_onthaalouder",
        "Breadcrumb1": "babysitten",
        "Breadcrumb1category": "Babysitten",
        "Breadcrumb2": "onthaalouder",
        "Breadcrumb2category": "Onthaalouder",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw onthaalouder",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale onthaalouder via Taskbooker",
        "HeadlineDynamicContent": "Enkele onthaalouders die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Via Taskbooker vind je eenvoudig een onthaalouder in jouw buurt. Je kiest zelf wie je je kinderen toevertrouwt. Via Taskbooker kom je in contact met verschillende mensen die jou kunnen helpen. Daarna kies je zelf je ideale onthaalouder.",
        "Paragraph2": "Taskbooker is een netwerk van mensen die elkaar willen helpen. Op Taskbooker vind je alle onthaalouders die jou willen helpen. Nadat je op Taskbooker hebt aangegeven wanneer je een onthaalouder nodig hebt, brengen wij je in contact met geschikte onthaalouders in jouw buurt",
        "Paragraph3": "Een onthaalouder vinden in jouw buurt was nog nooit zo eenvoudig. Wil je enkele vragen stellen aan de onthaalouders die je zouden kunnen helpen? Geen probleem. Je hebt rechtstreeks contact met verschillende personen in jouw buurt en spreekt ook zelf een prijs met hen af.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/babysitten/onthaalouder"
      },
      "www_taskbooker_be_babysitten_oppas": {
        "key": "www_taskbooker_be_babysitten_oppas",
        "Breadcrumb1": "babysitten",
        "Breadcrumb1category": "Babysitten",
        "Breadcrumb2": "oppas",
        "Breadcrumb2category": "Babysit aan huis",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw kinderoppas",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale kinderoppas via Taskbooker",
        "HeadlineDynamicContent": "Enkele Taskers gespecialiseerd in kinderoppas",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Via Taskbooker vind je eenvoudig een oppas in jouw buurt. Je kiest zelf op wie je wil vertrouwen. Via Taskbooker kom je in contact met verschillende mensen die jou kunnen helpen. Daarna kies je zelf je ideale oppas.",
        "Paragraph2": "Taskbooker is een netwerk van mensen die elkaar willen helpen. Op Taskbooker vind je snel een oppas die jou wil helpen. Nadat je op Taskbooker hebt aangegeven wanneer je een oppas kan gebruiken, brengen wij je in contact met geschikte personen in jouw buurt",
        "Paragraph3": "Een oppas vinden in jouw buurt ging nog nooit zo vlot. Heb je specifieke vragen of opmerkingen voor je oppas? Geen probleem. Je hebt rechtstreeks contact met verschillende personen in jouw buurt en spreekt ook zelf een prijs met hen af.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/babysitten/oppas"
      },
      "www_taskbooker_be_cateraar": {
        "key": "www_taskbooker_be_cateraar",
        "Breadcrumb1": "cateraar",
        "Breadcrumb1category": "Catering, voeding en maaltijden",
        "Breadcrumb2": "",
        "Breadcrumb2category": "Bereide maaltijden, take-away",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw cateraar",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale cateraar via Taskbooker",
        "HeadlineDynamicContent": "Enkele cateraars die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Geef je een feestje, of heb je gewoon zelf eens geen zin om te koken? Via Taskbooker vind je snel een cateraar in jouw buurt. Niet 'exclusief voor fancy people', gewoon betaalbaar en lekker eten bij jou thuis.",
        "Paragraph2": "Taskbooker brengt mensen die wat meer tijd voor zichzelf willen samen met mensen die een centje willen bijverdienen. Zo zijn er heel wat mensen in jouw buurt die via Taskbooker bijverdienen als cateraar, en jij kan daar heerlijk van genieten door bij hen maaltijden te bestellen.",
        "Paragraph3": "Taskbooker brengt je in contact met cateraars in jouw buurt, maar je kiest zelf bij wie je bestelt en tegen welke prijs. We zorgen ervoor dat je ruime keuze hebt, maar jij bent de baas.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/cateraar"
      },
      "www_taskbooker_be_catering-en-maaltijden_buffet-aan-huis": {
        "key": "www_taskbooker_be_catering-en-maaltijden_buffet-aan-huis",
        "Breadcrumb1": "catering-en-maaltijden",
        "Breadcrumb1category": "Catering, voeding en maaltijden",
        "Breadcrumb2": "buffet-aan-huis",
        "Breadcrumb2category": "Bereide maaltijden, take-away",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind Taskers voor buffet aan huis",
        "CityPostalcode": "",
        "Headline": "Boek je eigen buffet aan huis via Taskbooker",
        "HeadlineDynamicContent": "Enkele Taskers gespecialiseerd in buffet aan huis",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Tijd voor een feestje? Dan kan heerlijk eten niet ontbreken. Via Taskbooker boek je eenvoudig een cateraar in jouw buurt, zo kan jij voor de versiering zorgen terwijl iemand anders een heerlijk buffet voor je aan huis brengt!",
        "Paragraph2": "Taskbooker verzamelt alle hobbykoks in jouw buurt op Ã©Ã©n platform met Ã©Ã©n doel: jou helpen. Naast cateraars kan je via Taskbooker ook iemand vinden om foto's te trekken op je feest, iemand die je kan schminken, enzovoort. Tuinfeestje? No problem, ook een tuinman vind je eenvoudig via Taskbooker. Je buffet wordt alvast zo aan huis geleverd. Laat die gasten dus maar komen.",
        "Paragraph3": "Dankzij Taskbooker kom je snel in contact met mensen in jouw buurt die je kunnen helpen door een buffet aan huis te leveren. Je spreekt zelf een prijs af met hen, en betaalt op voorhand via Taskbooker.be. We houden je geld even bij en storten het na uitvoering van de taak door naar je Tasker.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/catering-en-maaltijden/buffet-aan-huis"
      },
      "www_taskbooker_be_catering-en-maaltijden_buffet-op-locatie": {
        "key": "www_taskbooker_be_catering-en-maaltijden_buffet-op-locatie",
        "Breadcrumb1": "catering-en-maaltijden",
        "Breadcrumb1category": "Catering, voeding en maaltijden",
        "Breadcrumb2": "buffet-op-locatie",
        "Breadcrumb2category": "Koken op locatie",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind Taskers voor buffet op locatie",
        "CityPostalcode": "",
        "Headline": "Boek je eigen buffet op locatie via Taskbooker",
        "HeadlineDynamicContent": "Enkele Taskers gespecialiseerd in buffet op locatie",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Tijd voor een feestje? Dan kan heerlijk eten niet ontbreken. Via Taskbooker boek je eenvoudig een cateraar in jouw buurt, zo kan jij voor de versiering zorgen terwijl iemand anders een heerlijk buffet voor je op locatie brengt!",
        "Paragraph2": "Taskbooker verzamelt alle hobbykoks in jouw buurt op Ã©Ã©n platform met Ã©Ã©n doel: jou helpen. Naast cateraars kan je via Taskbooker ook iemand vinden om foto's te trekken op je feest, iemand die je kan schminken, enzovoort. Tuinfeestje? No problem, ook een tuinman vind je eenvoudig via Taskbooker. Je buffet wordt alvast op locatie geleverd. Laat die gasten dus maar komen.",
        "Paragraph3": "Dankzij Taskbooker kom je snel in contact met mensen in jouw buurt die bijvoorbeeld een buffet leveren op locatie. Je spreekt zelf een prijs af met hen, en betaalt op voorhand via Taskbooker.be. We houden je geld even bij en storten het na uitvoering van de taak door naar je Tasker.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/catering-en-maaltijden/buffet-op-locatie"
      },
      "www_taskbooker_be_catering-en-maaltijden_traiteur-aan-huis": {
        "key": "www_taskbooker_be_catering-en-maaltijden_traiteur-aan-huis",
        "Breadcrumb1": "catering-en-maaltijden",
        "Breadcrumb1category": "Catering, voeding en maaltijden",
        "Breadcrumb2": "traiteur-aan-huis",
        "Breadcrumb2category": "Bereide maaltijden, take-away",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw traiteur aan huis",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale traiteur aan huis via Taskbooker",
        "HeadlineDynamicContent": "Enkele traiteurs aan huis die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Tijd voor een feestje? Dan kan heerlijk eten niet ontbreken. Via Taskbooker boek je eenvoudig een cateraar in jouw buurt, zo kan jij voor de versiering zorgen terwijl je helemaal kan vertrouwen op je traiteur aan huis.",
        "Paragraph2": "Taskbooker verzamelt alle hobbykoks in jouw buurt op Ã©Ã©n platform met Ã©Ã©n doel: jou helpen. Naast cateraars kan je via Taskbooker ook iemand vinden om foto's te trekken op je feest, iemand die je kan schminken, enzovoort. Tuinfeestje? No problem, ook een tuinman vind je eenvoudig via Taskbooker. Je traiteur komt in ieder geval al aan huis. Laat die gasten dus maar komen.",
        "Paragraph3": "Dankzij Taskbooker kom je snel in contact met mensen in jouw buurt die je kunnen helpen als 'traiteur aan huis'. Je spreekt zelf een prijs af met hen, en betaalt op voorhand via Taskbooker.be. We houden je geld even bij en storten het na uitvoering van de taak door naar je Tasker.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/catering-en-maaltijden/traiteur-aan-huis"
      },
      "www_taskbooker_be_catering-en-maaltijden_traiteur-op-locatie": {
        "key": "www_taskbooker_be_catering-en-maaltijden_traiteur-op-locatie",
        "Breadcrumb1": "catering-en-maaltijden",
        "Breadcrumb1category": "Catering, voeding en maaltijden",
        "Breadcrumb2": "traiteur-op-locatie",
        "Breadcrumb2category": "Koken op locatie",
        "Breadcrumb3": "",
        "Breadcrumb3category": "",
        "Bullet1": "Vind hulp op jouw maat",
        "Bullet2": "Mensen uit jouw buurt",
        "Bullet3": "Veilige betaling",
        "Bullet4": "Verzekerd en met plezier gedaan",
        "CTAtext": "Vind jouw traiteur op locatie",
        "CityPostalcode": "",
        "Headline": "Boek jouw ideale traiteur op locatie via Taskbooker",
        "HeadlineDynamicContent": "Enkele traiteurs op locatie die jou willen helpen",
        "NameReview1": "Marc P.",
        "NameReview2": "Nathalie M.",
        "NameReview3": "Patrick C.",
        "Paragraph1": "Tijd voor een feestje? Dan kan heerlijk eten niet ontbreken. Via Taskbooker boek je eenvoudig een cateraar in jouw buurt, zo kan jij voor de versiering zorgen terwijl je helemaal kan vertrouwen op je traiteur op locatie.",
        "Paragraph2": "Taskbooker verzamelt alle hobbykoks in jouw buurt op Ã©Ã©n platform met Ã©Ã©n doel: jou helpen. Naast cateraars kan je via Taskbooker ook iemand vinden om foto's te trekken op je feest, iemand die je kan schminken, enzovoort. Tuinfeestje? No problem, ook een tuinman vind je eenvoudig via Taskbooker. Je traiteur komt in ieder geval al op jouw locatie. Laat die gasten dus maar komen.",
        "Paragraph3": "Dankzij Taskbooker kom je snel in contact met mensen in jouw buurt die je kunnen helpen als 'traiteur op locatie'. Je spreekt zelf een prijs af met hen, en betaalt op voorhand via Taskbooker.be. We houden je geld even bij en storten het na uitvoering van de taak door naar je Tasker.",
        "Province": "",
        "Review1": "Taskbooker werkt super eenvoudig! Registreren, uitvoerders zoeken, en het was in orde.",
        "Review2": "Ik vond het aanvankelijk vreemd om op voorhand te betalen aan Taskbooker. Toen ik door had dat ze het geld niet meteen doorstorten naar de uitvoerder was ik wel helemaal gerustgesteld. En ik moet zeggen: het werkt perfect!",
        "Review3": "Nooit gedacht dat ik een tuinman kon vinden voor het onderhoud van m'n relatief kleine tuin. Maar via Taskbooker was het geen probleem",
        "URL": "www.taskbooker.be/catering-en-maaltijden/traiteur-op-locatie"
      }
    }
  }